[2019-06-05 12:33:05 +0200] [63224] [INFO] Starting gunicorn 19.9.0
[2019-06-05 12:33:05 +0200] [63224] [INFO] Listening at: http://127.0.0.1:9995 (63224)
[2019-06-05 12:33:05 +0200] [63224] [INFO] Using worker: sync
[2019-06-05 12:33:05 +0200] [63227] [INFO] Booting worker with pid: 63227
[2019-06-05 12:33:05 +0200] [63227] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/main.py", line 21
    gunicorn_logger = logging.getLogger(‘gunicorn.error’)
                                                ^
SyntaxError: invalid character in identifier
[2019-06-05 12:33:05 +0200] [63227] [INFO] Worker exiting (pid: 63227)
[2019-06-05 12:33:05 +0200] [63224] [INFO] Shutting down: Master
[2019-06-05 12:33:05 +0200] [63224] [INFO] Reason: Worker failed to boot.
[2019-06-05 12:33:57 +0200] [63231] [INFO] Starting gunicorn 19.9.0
[2019-06-05 12:33:57 +0200] [63231] [INFO] Listening at: http://127.0.0.1:9995 (63231)
[2019-06-05 12:33:57 +0200] [63231] [INFO] Using worker: sync
[2019-06-05 12:33:57 +0200] [63234] [INFO] Booting worker with pid: 63234
[2019-06-05 12:33:57 +0200] [63234] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/main.py", line 21
    app.logger.handlers = gunicorn_logger.handlers
                                                 ^
IndentationError: unindent does not match any outer indentation level
[2019-06-05 12:33:57 +0200] [63234] [INFO] Worker exiting (pid: 63234)
[2019-06-05 12:33:57 +0200] [63231] [INFO] Shutting down: Master
[2019-06-05 12:33:57 +0200] [63231] [INFO] Reason: Worker failed to boot.
[2019-06-05 12:34:33 +0200] [63237] [INFO] Starting gunicorn 19.9.0
[2019-06-05 12:34:33 +0200] [63237] [INFO] Listening at: http://127.0.0.1:9995 (63237)
[2019-06-05 12:34:33 +0200] [63237] [INFO] Using worker: sync
[2019-06-05 12:34:33 +0200] [63240] [INFO] Booting worker with pid: 63240
[2019-06-05 12:44:04 +0200] [63237] [INFO] Handling signal: int
[2019-06-05 12:44:04 +0200] [63240] [INFO] Worker exiting (pid: 63240)
[2019-06-05 12:44:05 +0200] [63237] [INFO] Shutting down: Master
[2019-06-05 12:44:08 +0200] [63301] [INFO] Starting gunicorn 19.9.0
[2019-06-05 12:44:08 +0200] [63301] [INFO] Listening at: http://127.0.0.1:9995 (63301)
[2019-06-05 12:44:08 +0200] [63301] [INFO] Using worker: sync
[2019-06-05 12:44:08 +0200] [63304] [INFO] Booting worker with pid: 63304
[2019-06-05 12:44:10 +0200] [63304] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/main.py", line 5, in <module>
    from bokeh_epele_model import modify_epele_doc
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/bokeh_epele_model.py", line 22, in <module>
    print(app)
NameError: name 'app' is not defined
[2019-06-05 12:44:10 +0200] [63304] [INFO] Worker exiting (pid: 63304)
[2019-06-05 12:44:10 +0200] [63301] [INFO] Shutting down: Master
[2019-06-05 12:44:10 +0200] [63301] [INFO] Reason: Worker failed to boot.
[2019-06-05 12:50:05 +0200] [63329] [INFO] Starting gunicorn 19.9.0
[2019-06-05 12:50:05 +0200] [63329] [INFO] Listening at: http://127.0.0.1:9995 (63329)
[2019-06-05 12:50:05 +0200] [63329] [INFO] Using worker: sync
[2019-06-05 12:50:05 +0200] [63332] [INFO] Booting worker with pid: 63332
[2019-06-05 12:50:50 +0200] [63329] [CRITICAL] WORKER TIMEOUT (pid:63332)
[2019-06-05 12:50:50 +0200] [63332] [INFO] Worker exiting (pid: 63332)
[2019-06-05 12:50:51 +0200] [63336] [INFO] Booting worker with pid: 63336
[2019-06-05 12:52:10 +0200] [63329] [INFO] Handling signal: int
[2019-06-05 12:52:10 +0200] [63336] [INFO] Worker exiting (pid: 63336)
[2019-06-05 12:52:12 +0200] [63329] [INFO] Shutting down: Master
[2019-06-05 12:52:16 +0200] [63348] [INFO] Starting gunicorn 19.9.0
[2019-06-05 12:52:16 +0200] [63348] [INFO] Listening at: http://127.0.0.1:9995 (63348)
[2019-06-05 12:52:16 +0200] [63348] [INFO] Using worker: sync
[2019-06-05 12:52:16 +0200] [63351] [INFO] Booting worker with pid: 63351
[2019-06-05 12:53:20 +0200] [63348] [INFO] Handling signal: int
[2019-06-05 12:53:20 +0200] [63351] [INFO] Worker exiting (pid: 63351)
[2019-06-05 12:53:21 +0200] [63348] [INFO] Shutting down: Master
[2019-06-05 12:53:23 +0200] [63364] [INFO] Starting gunicorn 19.9.0
[2019-06-05 12:53:23 +0200] [63364] [INFO] Listening at: http://127.0.0.1:9995 (63364)
[2019-06-05 12:53:23 +0200] [63364] [INFO] Using worker: sync
[2019-06-05 12:53:23 +0200] [63367] [INFO] Booting worker with pid: 63367
[2019-06-05 12:53:33 +0200] [63364] [INFO] Handling signal: int
[2019-06-05 12:53:33 +0200] [63367] [INFO] Worker exiting (pid: 63367)
[2019-06-05 12:53:34 +0200] [63364] [INFO] Shutting down: Master
[2019-06-05 12:54:02 +0200] [63369] [INFO] Starting gunicorn 19.9.0
[2019-06-05 12:54:02 +0200] [63369] [INFO] Listening at: http://127.0.0.1:9995 (63369)
[2019-06-05 12:54:02 +0200] [63369] [INFO] Using worker: sync
[2019-06-05 12:54:02 +0200] [63372] [INFO] Booting worker with pid: 63372
[2019-06-05 12:54:43 +0200] [63369] [CRITICAL] WORKER TIMEOUT (pid:63372)
[2019-06-05 12:54:43 +0200] [63372] [INFO] Worker exiting (pid: 63372)
[2019-06-05 12:54:44 +0200] [63374] [INFO] Booting worker with pid: 63374
[2019-06-05 14:50:22 +0200] [63369] [CRITICAL] WORKER TIMEOUT (pid:63374)
[2019-06-05 14:50:22 +0200] [63374] [INFO] Worker exiting (pid: 63374)
[2019-06-05 14:50:23 +0200] [63387] [INFO] Booting worker with pid: 63387
[2019-06-05 14:52:09 +0200] [63369] [INFO] Handling signal: int
[2019-06-05 14:52:09 +0200] [63387] [INFO] Worker exiting (pid: 63387)
[2019-06-05 14:52:10 +0200] [63369] [INFO] Shutting down: Master
[2019-06-05 14:52:15 +0200] [63440] [INFO] Starting gunicorn 19.9.0
[2019-06-05 14:52:15 +0200] [63440] [INFO] Listening at: http://127.0.0.1:9995 (63440)
[2019-06-05 14:52:15 +0200] [63440] [INFO] Using worker: sync
[2019-06-05 14:52:15 +0200] [63443] [INFO] Booting worker with pid: 63443
[2019-06-05 14:58:21 +0200] [63440] [INFO] Handling signal: int
[2019-06-05 14:58:21 +0200] [63443] [INFO] Worker exiting (pid: 63443)
[2019-06-05 14:58:22 +0200] [63440] [INFO] Shutting down: Master
[2019-06-05 14:58:24 +0200] [63512] [INFO] Starting gunicorn 19.9.0
[2019-06-05 14:58:24 +0200] [63512] [INFO] Listening at: http://127.0.0.1:9995 (63512)
[2019-06-05 14:58:24 +0200] [63512] [INFO] Using worker: sync
[2019-06-05 14:58:24 +0200] [63515] [INFO] Booting worker with pid: 63515
[2019-06-05 14:59:10 +0200] [63512] [INFO] Handling signal: int
[2019-06-05 14:59:10 +0200] [63515] [INFO] Worker exiting (pid: 63515)
[2019-06-05 14:59:10 +0200] [63515] [INFO] Unhandled exception in main loop
Traceback (most recent call last):
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.run()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 124, in run
    self.run_for_one(timeout)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 83, in run_for_one
    self.wait(timeout)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 35, in wait
    ret = select.select(self.wait_fds, [], [], timeout)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 190, in handle_quit
    time.sleep(0.1)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 191, in handle_quit
    sys.exit(0)
SystemExit: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 203, in run
    self.manage_workers()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 545, in manage_workers
    self.spawn_workers()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 616, in spawn_workers
    self.spawn_worker()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 599, in spawn_worker
    self.log.info("Worker exiting (pid: %s)", worker.pid)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/glogging.py", line 271, in info
    self.error_log.info(msg, *args, **kwargs)
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1383, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1519, in _log
    self.handle(record)
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1529, in handle
    self.callHandlers(record)
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1590, in callHandlers
    if record.levelno >= hdlr.level:
AttributeError: 'list' object has no attribute 'level'
[2019-06-05 14:59:10 +0200] [63512] [INFO] Shutting down: Master
[2019-06-05 14:59:12 +0200] [63521] [INFO] Starting gunicorn 19.9.0
[2019-06-05 14:59:12 +0200] [63521] [INFO] Listening at: http://127.0.0.1:9995 (63521)
[2019-06-05 14:59:12 +0200] [63521] [INFO] Using worker: sync
[2019-06-05 14:59:12 +0200] [63525] [INFO] Booting worker with pid: 63525
[2019-06-05 14:59:52 +0200] [63521] [INFO] Handling signal: int
[2019-06-05 14:59:52 +0200] [63525] [INFO] Worker exiting (pid: 63525)
[2019-06-05 14:59:52 +0200] [63525] [INFO] Unhandled exception in main loop
Traceback (most recent call last):
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.run()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 124, in run
    self.run_for_one(timeout)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 83, in run_for_one
    self.wait(timeout)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 35, in wait
    ret = select.select(self.wait_fds, [], [], timeout)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 190, in handle_quit
    time.sleep(0.1)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 191, in handle_quit
    sys.exit(0)
SystemExit: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 203, in run
    self.manage_workers()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 545, in manage_workers
    self.spawn_workers()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 616, in spawn_workers
    self.spawn_worker()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 599, in spawn_worker
    self.log.info("Worker exiting (pid: %s)", worker.pid)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/glogging.py", line 271, in info
    self.error_log.info(msg, *args, **kwargs)
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1383, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1519, in _log
    self.handle(record)
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1529, in handle
    self.callHandlers(record)
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1590, in callHandlers
    if record.levelno >= hdlr.level:
AttributeError: 'list' object has no attribute 'level'
[2019-06-05 14:59:53 +0200] [63521] [INFO] Shutting down: Master
[2019-06-05 14:59:54 +0200] [63556] [INFO] Starting gunicorn 19.9.0
[2019-06-05 14:59:54 +0200] [63556] [INFO] Listening at: http://127.0.0.1:9995 (63556)
[2019-06-05 14:59:54 +0200] [63556] [INFO] Using worker: sync
[2019-06-05 14:59:54 +0200] [63559] [INFO] Booting worker with pid: 63559
[2019-06-05 15:06:07 +0200] [63556] [INFO] Handling signal: int
[2019-06-05 15:06:07 +0200] [63559] [INFO] Worker exiting (pid: 63559)
[2019-06-05 15:06:07 +0200] [63559] [INFO] Unhandled exception in main loop
Traceback (most recent call last):
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.run()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 124, in run
    self.run_for_one(timeout)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 83, in run_for_one
    self.wait(timeout)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 35, in wait
    ret = select.select(self.wait_fds, [], [], timeout)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 190, in handle_quit
    time.sleep(0.1)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 191, in handle_quit
    sys.exit(0)
SystemExit: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 203, in run
    self.manage_workers()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 545, in manage_workers
    self.spawn_workers()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 616, in spawn_workers
    self.spawn_worker()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 599, in spawn_worker
    self.log.info("Worker exiting (pid: %s)", worker.pid)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/glogging.py", line 271, in info
    self.error_log.info(msg, *args, **kwargs)
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1383, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1519, in _log
    self.handle(record)
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1529, in handle
    self.callHandlers(record)
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1590, in callHandlers
    if record.levelno >= hdlr.level:
AttributeError: 'list' object has no attribute 'level'
[2019-06-05 15:06:09 +0200] [63556] [INFO] Shutting down: Master
[2019-06-05 15:06:11 +0200] [63694] [INFO] Starting gunicorn 19.9.0
[2019-06-05 15:06:11 +0200] [63694] [INFO] Listening at: http://127.0.0.1:9995 (63694)
[2019-06-05 15:06:11 +0200] [63694] [INFO] Using worker: sync
[2019-06-05 15:06:11 +0200] [63698] [INFO] Booting worker with pid: 63698
[2019-06-05 15:06:14 +0200] [63698] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/main.py", line 24, in <module>
    tornado_handler = FileHandler('/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/logs/error_log.log')
NameError: name 'FileHandler' is not defined
[2019-06-05 15:06:14 +0200] [63698] [INFO] Worker exiting (pid: 63698)
[2019-06-05 15:06:14 +0200] [63694] [INFO] Shutting down: Master
[2019-06-05 15:06:14 +0200] [63694] [INFO] Reason: Worker failed to boot.
[2019-06-05 15:06:57 +0200] [63709] [INFO] Starting gunicorn 19.9.0
[2019-06-05 15:06:57 +0200] [63709] [INFO] Listening at: http://127.0.0.1:9995 (63709)
[2019-06-05 15:06:57 +0200] [63709] [INFO] Using worker: sync
[2019-06-05 15:06:57 +0200] [63712] [INFO] Booting worker with pid: 63712
[2019-06-05 15:06:58 +0200] [63712] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/main.py", line 4, in <module>
    from logging.handlers import FileHandler
ImportError: cannot import name 'FileHandler' from 'logging.handlers' (/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/handlers.py)
[2019-06-05 15:06:58 +0200] [63712] [INFO] Worker exiting (pid: 63712)
[2019-06-05 15:06:58 +0200] [63709] [INFO] Shutting down: Master
[2019-06-05 15:06:58 +0200] [63709] [INFO] Reason: Worker failed to boot.
[2019-06-05 15:07:50 +0200] [63722] [INFO] Starting gunicorn 19.9.0
[2019-06-05 15:07:50 +0200] [63722] [INFO] Listening at: http://127.0.0.1:9995 (63722)
[2019-06-05 15:07:50 +0200] [63722] [INFO] Using worker: sync
[2019-06-05 15:07:50 +0200] [63725] [INFO] Booting worker with pid: 63725
500 GET /bokeh_epele/autoload.js?bokeh-autoload-element=1001&bokeh-app-path=/bokeh_epele&bokeh-absolute-url=http://localhost:9090/bokeh_epele (::1) 256.16ms
[2019-06-05 15:17:05 +0200] [63722] [INFO] Handling signal: int
[2019-06-05 15:17:05 +0200] [63725] [INFO] Worker exiting (pid: 63725)
[2019-06-05 15:17:05 +0200] [63725] [INFO] Unhandled exception in main loop
Traceback (most recent call last):
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.run()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 124, in run
    self.run_for_one(timeout)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 83, in run_for_one
    self.wait(timeout)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 35, in wait
    ret = select.select(self.wait_fds, [], [], timeout)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 190, in handle_quit
    time.sleep(0.1)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 191, in handle_quit
    sys.exit(0)
SystemExit: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 203, in run
    self.manage_workers()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 545, in manage_workers
    self.spawn_workers()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 616, in spawn_workers
    self.spawn_worker()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 599, in spawn_worker
    self.log.info("Worker exiting (pid: %s)", worker.pid)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/glogging.py", line 271, in info
    self.error_log.info(msg, *args, **kwargs)
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1383, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1519, in _log
    self.handle(record)
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1529, in handle
    self.callHandlers(record)
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1590, in callHandlers
    if record.levelno >= hdlr.level:
AttributeError: 'list' object has no attribute 'level'
[2019-06-05 15:17:07 +0200] [63722] [INFO] Shutting down: Master
[2019-06-05 15:17:28 +0200] [63792] [INFO] Starting gunicorn 19.9.0
[2019-06-05 15:17:28 +0200] [63792] [INFO] Listening at: http://127.0.0.1:9995 (63792)
[2019-06-05 15:17:28 +0200] [63792] [INFO] Using worker: sync
[2019-06-05 15:17:28 +0200] [63795] [INFO] Booting worker with pid: 63795
Uncaught exception GET /bokeh_epele/autoload.js?bokeh-autoload-element=1001&bokeh-app-path=/bokeh_epele&bokeh-absolute-url=http://localhost:9090/bokeh_epele (::1)
HTTPServerRequest(protocol='http', host='localhost:9090', method='GET', uri='/bokeh_epele/autoload.js?bokeh-autoload-element=1001&bokeh-app-path=/bokeh_epele&bokeh-absolute-url=http://localhost:9090/bokeh_epele', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/tornado/web.py", line 1592, in _execute
    result = yield result
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/bokeh/server/views/autoload_js_handler.py", line 60, in get
    session = yield self.get_session()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/bokeh/server/views/session_handler.py", line 77, in get_session
    session = yield self.application_context.create_session_if_needed(session_id, self.request)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/tornado/gen.py", line 1147, in run
    yielded = self.gen.send(value)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/bokeh/server/contexts.py", line 215, in create_session_if_needed
    self._application.initialize_document(doc)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/bokeh/application/application.py", line 178, in initialize_document
    h.modify_document(doc)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/bokeh/application/handlers/function.py", line 133, in modify_document
    self._func(doc)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/bokeh_epele_model.py", line 130, in modify_epele_doc
    table = Table('all_data_orc', MetaData(bind=engine), autoload=True)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 457, in __new__
    metadata._remove_table(name, schema)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 249, in reraise
    raise value
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 452, in __new__
    table._init(name, metadata, *args, **kw)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 534, in _init
    include_columns, _extend_on=_extend_on)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 560, in _autoload
    _extend_on=_extend_on
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2055, in run_callable
    with self.contextual_connect() as conn:
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2123, in contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2158, in _wrap_pool_connect
    return fn()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 400, in connect
    return _ConnectionFairy._checkout(self)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 788, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 529, in checkout
    rec = pool._do_get()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 1193, in _do_get
    self._dec_overflow()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 249, in reraise
    raise value
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 1190, in _do_get
    return self._create_connection()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 347, in _create_connection
    return _ConnectionRecord(self)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 474, in __init__
    self.__connect(first_connect_check=True)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 671, in __connect
    connection = pool._invoke_creator(self)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 106, in connect
    return dialect.connect(*cargs, **cparams)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 412, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/Users/mikelamuchastegui/Documents/TFG/PyHive/pyhive/hive.py", line 94, in connect
    return Connection(*args, **kwargs)
  File "/Users/mikelamuchastegui/Documents/TFG/PyHive/pyhive/hive.py", line 192, in __init__
    self._transport.open()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/thrift_sasl/__init__.py", line 79, in open
    message=("Could not start SASL: %s" % self.sasl.getError()))
thrift.transport.TTransport.TTransportException: Could not start SASL: b'Error in sasl_client_start (-1) SASL(-1): generic failure: GSSAPI Error:  Miscellaneous failure (see text (No credentials cache file found)'
500 GET /bokeh_epele/autoload.js?bokeh-autoload-element=1001&bokeh-app-path=/bokeh_epele&bokeh-absolute-url=http://localhost:9090/bokeh_epele (::1) 1233.53ms
[2019-06-05 15:18:16 +0200] [63792] [CRITICAL] WORKER TIMEOUT (pid:63795)
[2019-06-05 15:18:16 +0200] [63795] [INFO] Worker exiting (pid: 63795)
[2019-06-05 15:18:16 +0200] [63795] [INFO] Unhandled exception in main loop
Traceback (most recent call last):
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.run()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 124, in run
    self.run_for_one(timeout)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 68, in run_for_one
    self.accept(listener)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 30, in accept
    self.handle(listener, client, addr)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 134, in handle
    req = six.next(parser)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.req_count)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/http/message.py", line 181, in __init__
    super(Request, self).__init__(cfg, unreader)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/http/message.py", line 54, in __init__
    unused = self.parse(self.unreader)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/http/message.py", line 193, in parse
    self.get_data(unreader, buf, stop=True)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/http/message.py", line 184, in get_data
    data = unreader.read()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/http/unreader.py", line 38, in read
    d = self.chunk()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/http/unreader.py", line 65, in chunk
    return self.sock.recv(self.mxchunk)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 196, in handle_abort
    sys.exit(1)
SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 203, in run
    self.manage_workers()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 545, in manage_workers
    self.spawn_workers()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 616, in spawn_workers
    self.spawn_worker()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 599, in spawn_worker
    self.log.info("Worker exiting (pid: %s)", worker.pid)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/glogging.py", line 271, in info
    self.error_log.info(msg, *args, **kwargs)
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1383, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1519, in _log
    self.handle(record)
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1529, in handle
    self.callHandlers(record)
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1590, in callHandlers
    if record.levelno >= hdlr.level:
AttributeError: 'list' object has no attribute 'level'
[2019-06-05 15:18:17 +0200] [63802] [INFO] Booting worker with pid: 63802
Uncaught exception GET /bokeh_epele/autoload.js?bokeh-autoload-element=1001&bokeh-app-path=/bokeh_epele&bokeh-absolute-url=http://localhost:9090/bokeh_epele (::1)
HTTPServerRequest(protocol='http', host='localhost:9090', method='GET', uri='/bokeh_epele/autoload.js?bokeh-autoload-element=1001&bokeh-app-path=/bokeh_epele&bokeh-absolute-url=http://localhost:9090/bokeh_epele', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/tornado/web.py", line 1592, in _execute
    result = yield result
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/bokeh/server/views/autoload_js_handler.py", line 60, in get
    session = yield self.get_session()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/bokeh/server/views/session_handler.py", line 77, in get_session
    session = yield self.application_context.create_session_if_needed(session_id, self.request)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/tornado/gen.py", line 1147, in run
    yielded = self.gen.send(value)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/bokeh/server/contexts.py", line 215, in create_session_if_needed
    self._application.initialize_document(doc)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/bokeh/application/application.py", line 178, in initialize_document
    h.modify_document(doc)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/bokeh/application/handlers/function.py", line 133, in modify_document
    self._func(doc)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/bokeh_epele_model.py", line 130, in modify_epele_doc
    table = Table('all_data_orc', MetaData(bind=engine), autoload=True)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 457, in __new__
    metadata._remove_table(name, schema)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 249, in reraise
    raise value
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 452, in __new__
    table._init(name, metadata, *args, **kw)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 534, in _init
    include_columns, _extend_on=_extend_on)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 560, in _autoload
    _extend_on=_extend_on
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2055, in run_callable
    with self.contextual_connect() as conn:
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2123, in contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2158, in _wrap_pool_connect
    return fn()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 400, in connect
    return _ConnectionFairy._checkout(self)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 788, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 529, in checkout
    rec = pool._do_get()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 1193, in _do_get
    self._dec_overflow()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 249, in reraise
    raise value
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 1190, in _do_get
    return self._create_connection()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 347, in _create_connection
    return _ConnectionRecord(self)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 474, in __init__
    self.__connect(first_connect_check=True)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 671, in __connect
    connection = pool._invoke_creator(self)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 106, in connect
    return dialect.connect(*cargs, **cparams)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 412, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/Users/mikelamuchastegui/Documents/TFG/PyHive/pyhive/hive.py", line 94, in connect
    return Connection(*args, **kwargs)
  File "/Users/mikelamuchastegui/Documents/TFG/PyHive/pyhive/hive.py", line 192, in __init__
    self._transport.open()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/thrift_sasl/__init__.py", line 79, in open
    message=("Could not start SASL: %s" % self.sasl.getError()))
thrift.transport.TTransport.TTransportException: Could not start SASL: b'Error in sasl_client_start (-1) SASL(-1): generic failure: GSSAPI Error:  Miscellaneous failure (see text (No credentials cache file found)'
500 GET /bokeh_epele/autoload.js?bokeh-autoload-element=1001&bokeh-app-path=/bokeh_epele&bokeh-absolute-url=http://localhost:9090/bokeh_epele (::1) 257.50ms
Uncaught exception GET /bokeh_epele/autoload.js?bokeh-autoload-element=1002&bokeh-app-path=/bokeh_epele&bokeh-absolute-url=http://localhost:9090/bokeh_epele (::1)
HTTPServerRequest(protocol='http', host='localhost:9090', method='GET', uri='/bokeh_epele/autoload.js?bokeh-autoload-element=1002&bokeh-app-path=/bokeh_epele&bokeh-absolute-url=http://localhost:9090/bokeh_epele', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/tornado/web.py", line 1592, in _execute
    result = yield result
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/bokeh/server/views/autoload_js_handler.py", line 60, in get
    session = yield self.get_session()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/bokeh/server/views/session_handler.py", line 77, in get_session
    session = yield self.application_context.create_session_if_needed(session_id, self.request)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/tornado/gen.py", line 1147, in run
    yielded = self.gen.send(value)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/bokeh/server/contexts.py", line 215, in create_session_if_needed
    self._application.initialize_document(doc)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/bokeh/application/application.py", line 178, in initialize_document
    h.modify_document(doc)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/bokeh/application/handlers/function.py", line 133, in modify_document
    self._func(doc)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/bokeh_epele_model.py", line 130, in modify_epele_doc
    table = Table('all_data_orc', MetaData(bind=engine), autoload=True)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 457, in __new__
    metadata._remove_table(name, schema)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 249, in reraise
    raise value
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 452, in __new__
    table._init(name, metadata, *args, **kw)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 534, in _init
    include_columns, _extend_on=_extend_on)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 560, in _autoload
    _extend_on=_extend_on
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2055, in run_callable
    with self.contextual_connect() as conn:
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2123, in contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2158, in _wrap_pool_connect
    return fn()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 400, in connect
    return _ConnectionFairy._checkout(self)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 788, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 529, in checkout
    rec = pool._do_get()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 1193, in _do_get
    self._dec_overflow()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 249, in reraise
    raise value
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 1190, in _do_get
    return self._create_connection()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 347, in _create_connection
    return _ConnectionRecord(self)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 474, in __init__
    self.__connect(first_connect_check=True)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 671, in __connect
    connection = pool._invoke_creator(self)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 106, in connect
    return dialect.connect(*cargs, **cparams)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 412, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/Users/mikelamuchastegui/Documents/TFG/PyHive/pyhive/hive.py", line 94, in connect
    return Connection(*args, **kwargs)
  File "/Users/mikelamuchastegui/Documents/TFG/PyHive/pyhive/hive.py", line 192, in __init__
    self._transport.open()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/thrift_sasl/__init__.py", line 79, in open
    message=("Could not start SASL: %s" % self.sasl.getError()))
thrift.transport.TTransport.TTransportException: Could not start SASL: b'Error in sasl_client_start (-1) SASL(-1): generic failure: GSSAPI Error:  Miscellaneous failure (see text (No credentials cache file found (negative cache))'
500 GET /bokeh_epele/autoload.js?bokeh-autoload-element=1002&bokeh-app-path=/bokeh_epele&bokeh-absolute-url=http://localhost:9090/bokeh_epele (::1) 28.41ms
Uncaught exception GET /bokeh_epele/autoload.js?bokeh-autoload-element=1003&bokeh-app-path=/bokeh_epele&bokeh-absolute-url=http://localhost:9090/bokeh_epele (::1)
HTTPServerRequest(protocol='http', host='localhost:9090', method='GET', uri='/bokeh_epele/autoload.js?bokeh-autoload-element=1003&bokeh-app-path=/bokeh_epele&bokeh-absolute-url=http://localhost:9090/bokeh_epele', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/tornado/web.py", line 1592, in _execute
    result = yield result
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/bokeh/server/views/autoload_js_handler.py", line 60, in get
    session = yield self.get_session()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/bokeh/server/views/session_handler.py", line 77, in get_session
    session = yield self.application_context.create_session_if_needed(session_id, self.request)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/tornado/gen.py", line 1147, in run
    yielded = self.gen.send(value)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/bokeh/server/contexts.py", line 215, in create_session_if_needed
    self._application.initialize_document(doc)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/bokeh/application/application.py", line 178, in initialize_document
    h.modify_document(doc)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/bokeh/application/handlers/function.py", line 133, in modify_document
    self._func(doc)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/bokeh_epele_model.py", line 130, in modify_epele_doc
    table = Table('all_data_orc', MetaData(bind=engine), autoload=True)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 457, in __new__
    metadata._remove_table(name, schema)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 249, in reraise
    raise value
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 452, in __new__
    table._init(name, metadata, *args, **kw)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 534, in _init
    include_columns, _extend_on=_extend_on)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 560, in _autoload
    _extend_on=_extend_on
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2055, in run_callable
    with self.contextual_connect() as conn:
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2123, in contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2158, in _wrap_pool_connect
    return fn()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 400, in connect
    return _ConnectionFairy._checkout(self)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 788, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 529, in checkout
    rec = pool._do_get()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 1193, in _do_get
    self._dec_overflow()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 249, in reraise
    raise value
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 1190, in _do_get
    return self._create_connection()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 347, in _create_connection
    return _ConnectionRecord(self)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 474, in __init__
    self.__connect(first_connect_check=True)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 671, in __connect
    connection = pool._invoke_creator(self)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 106, in connect
    return dialect.connect(*cargs, **cparams)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 412, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/Users/mikelamuchastegui/Documents/TFG/PyHive/pyhive/hive.py", line 94, in connect
    return Connection(*args, **kwargs)
  File "/Users/mikelamuchastegui/Documents/TFG/PyHive/pyhive/hive.py", line 192, in __init__
    self._transport.open()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/thrift_sasl/__init__.py", line 79, in open
    message=("Could not start SASL: %s" % self.sasl.getError()))
thrift.transport.TTransport.TTransportException: Could not start SASL: b'Error in sasl_client_start (-1) SASL(-1): generic failure: GSSAPI Error:  Miscellaneous failure (see text (No credentials cache file found (negative cache))'
500 GET /bokeh_epele/autoload.js?bokeh-autoload-element=1003&bokeh-app-path=/bokeh_epele&bokeh-absolute-url=http://localhost:9090/bokeh_epele (::1) 58.32ms
[2019-06-05 15:19:40 +0200] [63792] [INFO] Handling signal: int
[2019-06-05 15:19:40 +0200] [63802] [INFO] Worker exiting (pid: 63802)
[2019-06-05 15:19:40 +0200] [63802] [INFO] Unhandled exception in main loop
Traceback (most recent call last):
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.run()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 124, in run
    self.run_for_one(timeout)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 83, in run_for_one
    self.wait(timeout)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 35, in wait
    ret = select.select(self.wait_fds, [], [], timeout)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 190, in handle_quit
    time.sleep(0.1)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 191, in handle_quit
    sys.exit(0)
SystemExit: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 212, in run
    self.manage_workers()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 545, in manage_workers
    self.spawn_workers()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 616, in spawn_workers
    self.spawn_worker()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 599, in spawn_worker
    self.log.info("Worker exiting (pid: %s)", worker.pid)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/glogging.py", line 271, in info
    self.error_log.info(msg, *args, **kwargs)
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1383, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1519, in _log
    self.handle(record)
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1529, in handle
    self.callHandlers(record)
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1590, in callHandlers
    if record.levelno >= hdlr.level:
AttributeError: 'list' object has no attribute 'level'
[2019-06-05 15:19:42 +0200] [63792] [INFO] Shutting down: Master
[2019-06-05 15:19:58 +0200] [63804] [INFO] Starting gunicorn 19.9.0
[2019-06-05 15:19:58 +0200] [63804] [INFO] Listening at: http://127.0.0.1:9995 (63804)
[2019-06-05 15:19:58 +0200] [63804] [INFO] Using worker: sync
[2019-06-05 15:19:58 +0200] [63807] [INFO] Booting worker with pid: 63807
Uncaught exception GET /bokeh_epele/autoload.js?bokeh-autoload-element=1001&bokeh-app-path=/bokeh_epele&bokeh-absolute-url=http://localhost:9090/bokeh_epele (::1)
HTTPServerRequest(protocol='http', host='localhost:9090', method='GET', uri='/bokeh_epele/autoload.js?bokeh-autoload-element=1001&bokeh-app-path=/bokeh_epele&bokeh-absolute-url=http://localhost:9090/bokeh_epele', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/tornado/web.py", line 1592, in _execute
    result = yield result
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/bokeh/server/views/autoload_js_handler.py", line 60, in get
    session = yield self.get_session()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/bokeh/server/views/session_handler.py", line 77, in get_session
    session = yield self.application_context.create_session_if_needed(session_id, self.request)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/tornado/gen.py", line 1147, in run
    yielded = self.gen.send(value)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/bokeh/server/contexts.py", line 215, in create_session_if_needed
    self._application.initialize_document(doc)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/bokeh/application/application.py", line 178, in initialize_document
    h.modify_document(doc)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/bokeh/application/handlers/function.py", line 133, in modify_document
    self._func(doc)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/bokeh_epele_model.py", line 130, in modify_epele_doc
    table = Table('all_data_orc', MetaData(bind=engine), autoload=True)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 457, in __new__
    metadata._remove_table(name, schema)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 249, in reraise
    raise value
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 452, in __new__
    table._init(name, metadata, *args, **kw)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 534, in _init
    include_columns, _extend_on=_extend_on)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 560, in _autoload
    _extend_on=_extend_on
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2055, in run_callable
    with self.contextual_connect() as conn:
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2123, in contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2158, in _wrap_pool_connect
    return fn()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 400, in connect
    return _ConnectionFairy._checkout(self)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 788, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 529, in checkout
    rec = pool._do_get()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 1193, in _do_get
    self._dec_overflow()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 249, in reraise
    raise value
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 1190, in _do_get
    return self._create_connection()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 347, in _create_connection
    return _ConnectionRecord(self)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 474, in __init__
    self.__connect(first_connect_check=True)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 671, in __connect
    connection = pool._invoke_creator(self)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 106, in connect
    return dialect.connect(*cargs, **cparams)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 412, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/Users/mikelamuchastegui/Documents/TFG/PyHive/pyhive/hive.py", line 94, in connect
    return Connection(*args, **kwargs)
  File "/Users/mikelamuchastegui/Documents/TFG/PyHive/pyhive/hive.py", line 192, in __init__
    self._transport.open()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/thrift_sasl/__init__.py", line 79, in open
    message=("Could not start SASL: %s" % self.sasl.getError()))
thrift.transport.TTransport.TTransportException: Could not start SASL: b'Error in sasl_client_start (-1) SASL(-1): generic failure: GSSAPI Error:  Miscellaneous failure (see text (No credentials cache file found)'
500 GET /bokeh_epele/autoload.js?bokeh-autoload-element=1001&bokeh-app-path=/bokeh_epele&bokeh-absolute-url=http://localhost:9090/bokeh_epele (::1) 1197.41ms
Uncaught exception GET /bokeh_epele/autoload.js?bokeh-autoload-element=1002&bokeh-app-path=/bokeh_epele&bokeh-absolute-url=http://localhost:9090/bokeh_epele (::1)
HTTPServerRequest(protocol='http', host='localhost:9090', method='GET', uri='/bokeh_epele/autoload.js?bokeh-autoload-element=1002&bokeh-app-path=/bokeh_epele&bokeh-absolute-url=http://localhost:9090/bokeh_epele', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/tornado/web.py", line 1592, in _execute
    result = yield result
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/bokeh/server/views/autoload_js_handler.py", line 60, in get
    session = yield self.get_session()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/bokeh/server/views/session_handler.py", line 77, in get_session
    session = yield self.application_context.create_session_if_needed(session_id, self.request)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/tornado/gen.py", line 1147, in run
    yielded = self.gen.send(value)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/bokeh/server/contexts.py", line 215, in create_session_if_needed
    self._application.initialize_document(doc)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/bokeh/application/application.py", line 178, in initialize_document
    h.modify_document(doc)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/bokeh/application/handlers/function.py", line 133, in modify_document
    self._func(doc)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/bokeh_epele_model.py", line 130, in modify_epele_doc
    table = Table('all_data_orc', MetaData(bind=engine), autoload=True)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 457, in __new__
    metadata._remove_table(name, schema)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 249, in reraise
    raise value
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 452, in __new__
    table._init(name, metadata, *args, **kw)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 534, in _init
    include_columns, _extend_on=_extend_on)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 560, in _autoload
    _extend_on=_extend_on
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2055, in run_callable
    with self.contextual_connect() as conn:
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2123, in contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2158, in _wrap_pool_connect
    return fn()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 400, in connect
    return _ConnectionFairy._checkout(self)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 788, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 529, in checkout
    rec = pool._do_get()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 1193, in _do_get
    self._dec_overflow()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 249, in reraise
    raise value
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 1190, in _do_get
    return self._create_connection()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 347, in _create_connection
    return _ConnectionRecord(self)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 474, in __init__
    self.__connect(first_connect_check=True)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 671, in __connect
    connection = pool._invoke_creator(self)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 106, in connect
    return dialect.connect(*cargs, **cparams)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 412, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/Users/mikelamuchastegui/Documents/TFG/PyHive/pyhive/hive.py", line 94, in connect
    return Connection(*args, **kwargs)
  File "/Users/mikelamuchastegui/Documents/TFG/PyHive/pyhive/hive.py", line 192, in __init__
    self._transport.open()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/thrift_sasl/__init__.py", line 79, in open
    message=("Could not start SASL: %s" % self.sasl.getError()))
thrift.transport.TTransport.TTransportException: Could not start SASL: b'Error in sasl_client_start (-1) SASL(-1): generic failure: GSSAPI Error:  Miscellaneous failure (see text (No credentials cache file found (negative cache))'
500 GET /bokeh_epele/autoload.js?bokeh-autoload-element=1002&bokeh-app-path=/bokeh_epele&bokeh-absolute-url=http://localhost:9090/bokeh_epele (::1) 15.06ms
[2019-06-05 15:21:50 +0200] [63804] [CRITICAL] WORKER TIMEOUT (pid:63807)
[2019-06-05 15:21:50 +0200] [63807] [INFO] Worker exiting (pid: 63807)
[2019-06-05 15:21:50 +0200] [63807] [INFO] Unhandled exception in main loop
Traceback (most recent call last):
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.run()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 124, in run
    self.run_for_one(timeout)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 68, in run_for_one
    self.accept(listener)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 30, in accept
    self.handle(listener, client, addr)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 134, in handle
    req = six.next(parser)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.req_count)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/http/message.py", line 181, in __init__
    super(Request, self).__init__(cfg, unreader)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/http/message.py", line 54, in __init__
    unused = self.parse(self.unreader)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/http/message.py", line 193, in parse
    self.get_data(unreader, buf, stop=True)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/http/message.py", line 184, in get_data
    data = unreader.read()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/http/unreader.py", line 38, in read
    d = self.chunk()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/http/unreader.py", line 65, in chunk
    return self.sock.recv(self.mxchunk)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 196, in handle_abort
    sys.exit(1)
SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 203, in run
    self.manage_workers()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 545, in manage_workers
    self.spawn_workers()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 616, in spawn_workers
    self.spawn_worker()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 599, in spawn_worker
    self.log.info("Worker exiting (pid: %s)", worker.pid)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/glogging.py", line 271, in info
    self.error_log.info(msg, *args, **kwargs)
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1383, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1519, in _log
    self.handle(record)
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1529, in handle
    self.callHandlers(record)
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1590, in callHandlers
    if record.levelno >= hdlr.level:
AttributeError: 'list' object has no attribute 'level'
[2019-06-05 15:21:51 +0200] [63848] [INFO] Booting worker with pid: 63848
[2019-06-05 15:24:03 +0200] [63804] [INFO] Handling signal: int
[2019-06-05 15:24:03 +0200] [63848] [INFO] Worker exiting (pid: 63848)
[2019-06-05 15:24:03 +0200] [63848] [INFO] Unhandled exception in main loop
Traceback (most recent call last):
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.run()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 124, in run
    self.run_for_one(timeout)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 83, in run_for_one
    self.wait(timeout)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 35, in wait
    ret = select.select(self.wait_fds, [], [], timeout)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 190, in handle_quit
    time.sleep(0.1)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 191, in handle_quit
    sys.exit(0)
SystemExit: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 212, in run
    self.manage_workers()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 545, in manage_workers
    self.spawn_workers()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 616, in spawn_workers
    self.spawn_worker()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 599, in spawn_worker
    self.log.info("Worker exiting (pid: %s)", worker.pid)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/glogging.py", line 271, in info
    self.error_log.info(msg, *args, **kwargs)
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1383, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1519, in _log
    self.handle(record)
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1529, in handle
    self.callHandlers(record)
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1590, in callHandlers
    if record.levelno >= hdlr.level:
AttributeError: 'list' object has no attribute 'level'
[2019-06-05 15:24:04 +0200] [63804] [INFO] Shutting down: Master
[2019-06-05 15:24:05 +0200] [63858] [INFO] Starting gunicorn 19.9.0
[2019-06-05 15:24:05 +0200] [63858] [INFO] Listening at: http://127.0.0.1:9995 (63858)
[2019-06-05 15:24:05 +0200] [63858] [INFO] Using worker: sync
[2019-06-05 15:24:05 +0200] [63862] [INFO] Booting worker with pid: 63862
[2019-06-05 15:24:08 +0200] [63862] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/main.py", line 34, in <module>
    app.logger.handlers.addHandler(gunicorn_logger.handlers)
AttributeError: 'list' object has no attribute 'addHandler'
[2019-06-05 15:24:08 +0200] [63862] [INFO] Worker exiting (pid: 63862)
[2019-06-05 15:24:08 +0200] [63858] [INFO] Shutting down: Master
[2019-06-05 15:24:08 +0200] [63858] [INFO] Reason: Worker failed to boot.
[2019-06-05 15:24:32 +0200] [63864] [INFO] Starting gunicorn 19.9.0
[2019-06-05 15:24:32 +0200] [63864] [INFO] Listening at: http://127.0.0.1:9995 (63864)
[2019-06-05 15:24:32 +0200] [63864] [INFO] Using worker: sync
[2019-06-05 15:24:32 +0200] [63867] [INFO] Booting worker with pid: 63867
Uncaught exception GET /bokeh_epele/autoload.js?bokeh-autoload-element=1001&bokeh-app-path=/bokeh_epele&bokeh-absolute-url=http://localhost:9090/bokeh_epele (::1)
HTTPServerRequest(protocol='http', host='localhost:9090', method='GET', uri='/bokeh_epele/autoload.js?bokeh-autoload-element=1001&bokeh-app-path=/bokeh_epele&bokeh-absolute-url=http://localhost:9090/bokeh_epele', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/tornado/web.py", line 1592, in _execute
    result = yield result
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/bokeh/server/views/autoload_js_handler.py", line 60, in get
    session = yield self.get_session()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/bokeh/server/views/session_handler.py", line 77, in get_session
    session = yield self.application_context.create_session_if_needed(session_id, self.request)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/tornado/gen.py", line 1147, in run
    yielded = self.gen.send(value)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/bokeh/server/contexts.py", line 215, in create_session_if_needed
    self._application.initialize_document(doc)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/bokeh/application/application.py", line 178, in initialize_document
    h.modify_document(doc)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/bokeh/application/handlers/function.py", line 133, in modify_document
    self._func(doc)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/bokeh_epele_model.py", line 130, in modify_epele_doc
    table = Table('all_data_orc', MetaData(bind=engine), autoload=True)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 457, in __new__
    metadata._remove_table(name, schema)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 249, in reraise
    raise value
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 452, in __new__
    table._init(name, metadata, *args, **kw)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 534, in _init
    include_columns, _extend_on=_extend_on)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 560, in _autoload
    _extend_on=_extend_on
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2055, in run_callable
    with self.contextual_connect() as conn:
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2123, in contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2158, in _wrap_pool_connect
    return fn()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 400, in connect
    return _ConnectionFairy._checkout(self)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 788, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 529, in checkout
    rec = pool._do_get()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 1193, in _do_get
    self._dec_overflow()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 249, in reraise
    raise value
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 1190, in _do_get
    return self._create_connection()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 347, in _create_connection
    return _ConnectionRecord(self)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 474, in __init__
    self.__connect(first_connect_check=True)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 671, in __connect
    connection = pool._invoke_creator(self)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 106, in connect
    return dialect.connect(*cargs, **cparams)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 412, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/Users/mikelamuchastegui/Documents/TFG/PyHive/pyhive/hive.py", line 94, in connect
    return Connection(*args, **kwargs)
  File "/Users/mikelamuchastegui/Documents/TFG/PyHive/pyhive/hive.py", line 192, in __init__
    self._transport.open()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/thrift_sasl/__init__.py", line 79, in open
    message=("Could not start SASL: %s" % self.sasl.getError()))
thrift.transport.TTransport.TTransportException: Could not start SASL: b'Error in sasl_client_start (-1) SASL(-1): generic failure: GSSAPI Error:  Miscellaneous failure (see text (No credentials cache file found)'
500 GET /bokeh_epele/autoload.js?bokeh-autoload-element=1001&bokeh-app-path=/bokeh_epele&bokeh-absolute-url=http://localhost:9090/bokeh_epele (::1) 211.65ms
Uncaught exception GET /bokeh_epele/autoload.js?bokeh-autoload-element=1002&bokeh-app-path=/bokeh_epele&bokeh-absolute-url=http://localhost:9090/bokeh_epele (::1)
HTTPServerRequest(protocol='http', host='localhost:9090', method='GET', uri='/bokeh_epele/autoload.js?bokeh-autoload-element=1002&bokeh-app-path=/bokeh_epele&bokeh-absolute-url=http://localhost:9090/bokeh_epele', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/tornado/web.py", line 1592, in _execute
    result = yield result
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/bokeh/server/views/autoload_js_handler.py", line 60, in get
    session = yield self.get_session()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/bokeh/server/views/session_handler.py", line 77, in get_session
    session = yield self.application_context.create_session_if_needed(session_id, self.request)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/tornado/gen.py", line 1147, in run
    yielded = self.gen.send(value)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/bokeh/server/contexts.py", line 215, in create_session_if_needed
    self._application.initialize_document(doc)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/bokeh/application/application.py", line 178, in initialize_document
    h.modify_document(doc)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/bokeh/application/handlers/function.py", line 133, in modify_document
    self._func(doc)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/bokeh_epele_model.py", line 130, in modify_epele_doc
    table = Table('all_data_orc', MetaData(bind=engine), autoload=True)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 457, in __new__
    metadata._remove_table(name, schema)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 249, in reraise
    raise value
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 452, in __new__
    table._init(name, metadata, *args, **kw)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 534, in _init
    include_columns, _extend_on=_extend_on)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 560, in _autoload
    _extend_on=_extend_on
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2055, in run_callable
    with self.contextual_connect() as conn:
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2123, in contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2158, in _wrap_pool_connect
    return fn()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 400, in connect
    return _ConnectionFairy._checkout(self)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 788, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 529, in checkout
    rec = pool._do_get()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 1193, in _do_get
    self._dec_overflow()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 249, in reraise
    raise value
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 1190, in _do_get
    return self._create_connection()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 347, in _create_connection
    return _ConnectionRecord(self)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 474, in __init__
    self.__connect(first_connect_check=True)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 671, in __connect
    connection = pool._invoke_creator(self)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 106, in connect
    return dialect.connect(*cargs, **cparams)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 412, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/Users/mikelamuchastegui/Documents/TFG/PyHive/pyhive/hive.py", line 94, in connect
    return Connection(*args, **kwargs)
  File "/Users/mikelamuchastegui/Documents/TFG/PyHive/pyhive/hive.py", line 192, in __init__
    self._transport.open()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/thrift_sasl/__init__.py", line 79, in open
    message=("Could not start SASL: %s" % self.sasl.getError()))
thrift.transport.TTransport.TTransportException: Could not start SASL: b'Error in sasl_client_start (-1) SASL(-1): generic failure: GSSAPI Error:  Miscellaneous failure (see text (No credentials cache file found (negative cache))'
500 GET /bokeh_epele/autoload.js?bokeh-autoload-element=1002&bokeh-app-path=/bokeh_epele&bokeh-absolute-url=http://localhost:9090/bokeh_epele (::1) 14.90ms
[2019-06-05 15:36:16 +0200] [63864] [INFO] Handling signal: int
[2019-06-05 15:36:16 +0200] [63867] [INFO] Worker exiting (pid: 63867)
[2019-06-05 15:36:17 +0200] [63864] [INFO] Shutting down: Master
[2019-06-05 15:36:18 +0200] [64229] [INFO] Starting gunicorn 19.9.0
[2019-06-05 15:36:18 +0200] [64229] [INFO] Listening at: http://127.0.0.1:9995 (64229)
[2019-06-05 15:36:18 +0200] [64229] [INFO] Using worker: sync
[2019-06-05 15:36:18 +0200] [64233] [INFO] Booting worker with pid: 64233
Uncaught exception GET /bokeh_epele/autoload.js?bokeh-autoload-element=1001&bokeh-app-path=/bokeh_epele&bokeh-absolute-url=http://localhost:9090/bokeh_epele (::1)
HTTPServerRequest(protocol='http', host='localhost:9090', method='GET', uri='/bokeh_epele/autoload.js?bokeh-autoload-element=1001&bokeh-app-path=/bokeh_epele&bokeh-absolute-url=http://localhost:9090/bokeh_epele', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/tornado/web.py", line 1592, in _execute
    result = yield result
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/bokeh/server/views/autoload_js_handler.py", line 60, in get
    session = yield self.get_session()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/bokeh/server/views/session_handler.py", line 77, in get_session
    session = yield self.application_context.create_session_if_needed(session_id, self.request)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/tornado/gen.py", line 1147, in run
    yielded = self.gen.send(value)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/bokeh/server/contexts.py", line 215, in create_session_if_needed
    self._application.initialize_document(doc)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/bokeh/application/application.py", line 178, in initialize_document
    h.modify_document(doc)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/bokeh/application/handlers/function.py", line 133, in modify_document
    self._func(doc)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/bokeh_epele_model.py", line 130, in modify_epele_doc
    table = Table('all_data_orc', MetaData(bind=engine), autoload=True)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 457, in __new__
    metadata._remove_table(name, schema)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 249, in reraise
    raise value
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 452, in __new__
    table._init(name, metadata, *args, **kw)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 534, in _init
    include_columns, _extend_on=_extend_on)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 560, in _autoload
    _extend_on=_extend_on
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2055, in run_callable
    with self.contextual_connect() as conn:
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2123, in contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2158, in _wrap_pool_connect
    return fn()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 400, in connect
    return _ConnectionFairy._checkout(self)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 788, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 529, in checkout
    rec = pool._do_get()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 1193, in _do_get
    self._dec_overflow()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 249, in reraise
    raise value
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 1190, in _do_get
    return self._create_connection()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 347, in _create_connection
    return _ConnectionRecord(self)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 474, in __init__
    self.__connect(first_connect_check=True)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/pool.py", line 671, in __connect
    connection = pool._invoke_creator(self)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 106, in connect
    return dialect.connect(*cargs, **cparams)
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 412, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/Users/mikelamuchastegui/Documents/TFG/PyHive/pyhive/hive.py", line 94, in connect
    return Connection(*args, **kwargs)
  File "/Users/mikelamuchastegui/Documents/TFG/PyHive/pyhive/hive.py", line 192, in __init__
    self._transport.open()
  File "/Users/mikelamuchastegui/Documents/TFG/Bokeh_Epele/venv/lib/python3.7/site-packages/thrift_sasl/__init__.py", line 79, in open
    message=("Could not start SASL: %s" % self.sasl.getError()))
thrift.transport.TTransport.TTransportException: Could not start SASL: b'Error in sasl_client_start (-1) SASL(-1): generic failure: GSSAPI Error:  Miscellaneous failure (see text (No credentials cache file found)'
500 GET /bokeh_epele/autoload.js?bokeh-autoload-element=1001&bokeh-app-path=/bokeh_epele&bokeh-absolute-url=http://localhost:9090/bokeh_epele (::1) 135.66ms
[2019-06-05 15:42:41 +0200] [64229] [INFO] Handling signal: int
[2019-06-05 15:42:41 +0200] [64233] [INFO] Worker exiting (pid: 64233)
[2019-06-05 15:42:41 +0200] [64229] [INFO] Shutting down: Master
200 GET /cartuja_second_descriptive/autoload.js?bokeh-autoload-element=1001&bokeh-app-path=/cartuja_second_descriptive&bokeh-absolute-url=http://localhost:9090/cartuja_second_descriptive (::1) 25866.62ms
101 GET /cartuja_second_descriptive/ws?bokeh-protocol-version=1.0&bokeh-session-id=do9bAsZsI93FtPoNtThClQXDTjxLyzQFFjVe8AoE0NMT (::1) 1.68ms
200 GET /cartuja_second_descriptive/autoload.js?bokeh-autoload-element=1001&bokeh-app-path=/cartuja_second_descriptive&bokeh-absolute-url=http://localhost:9090/cartuja_second_descriptive (::1) 24493.49ms
101 GET /cartuja_second_descriptive/ws?bokeh-protocol-version=1.0&bokeh-session-id=u8H8JZG57b4F1KmaLsIlbPuTuiDQboXUvkuWefZYrXnn (::1) 1.28ms
200 GET /static/js/bokeh-gl.min.js.map (::1) 10.07ms
200 GET /static/js/bokeh-widgets.min.js.map (::1) 29.98ms
200 GET /static/js/bokeh-tables.min.js.map (::1) 57.89ms
200 GET /static/js/bokeh.min.js.map (::1) 204.61ms
200 GET /cartuja_first_descriptive/autoload.js?bokeh-autoload-element=1001&bokeh-app-path=/cartuja_first_descriptive&bokeh-absolute-url=http://localhost:9090/cartuja_first_descriptive (::1) 3477.09ms
101 GET /cartuja_first_descriptive/ws?bokeh-protocol-version=1.0&bokeh-session-id=vgKu8pPtETjxf6REYDCAc2nnq2WRnpqgBiqVVaj9Likx (::1) 1.16ms
200 GET /cartuja_second_descriptive/autoload.js?bokeh-autoload-element=1460&bokeh-app-path=/cartuja_second_descriptive&bokeh-absolute-url=http://localhost:9090/cartuja_second_descriptive (::1) 21471.47ms
101 GET /cartuja_second_descriptive/ws?bokeh-protocol-version=1.0&bokeh-session-id=gDyw7RohJtpTFeTMCVRyrRZWLwpOUonpLhd0CpiUesT3 (::1) 0.97ms
200 GET /cartuja_second_descriptive/autoload.js?bokeh-autoload-element=1001&bokeh-app-path=/cartuja_second_descriptive&bokeh-absolute-url=http://localhost:9090/cartuja_second_descriptive (::1) 27711.04ms
101 GET /cartuja_second_descriptive/ws?bokeh-protocol-version=1.0&bokeh-session-id=0dYGsTJNY3JRqcLZjYqQx3agCO1FHdFzLdDv4a6BbuaB (::1) 1.41ms
